---
- hosts: www
  gather_facts: False

  pre_tasks:
    - debug: msg="Pre tasks section"

    - name: ANSIBLE PYTHON | install python 2
      raw: test -e /usr/bin/python || (type apt > /dev/null && apt -qqy update && apt install -qy python-minimal)
      become: yes

    - name:  UNPRIVILEGED USERS | Get acl dependency (ansible unprivileged user operations magic)
      package: name="acl"
      become: yes

    - name: gather facts
      setup:

  roles:
     - {
         role: "sa-docker"
       }
     - {
         role: "sa-cadvisor"
       }


  tasks:

    - debug: msg="Tasks section"

